### ISSUE TITLE
CI has not been running since 9/12

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GM-TestFramework#179]
### Description

Hello, it seems the custom runners are offline since 9/12 and the CIs are not running.

### Script Name

N/A

### Fact/Assert Name

N/A

### How reliably does this issue happen?

Always

**Comment by shichen85** [comment]
In the mean time, you can see that our CIs run against the Beta-I RSS and caught the following issues:
https://github.com/bscotch/ganary/actions/runs/11329711420 caught https://github.com/YoYoGames/GameMaker-Bugs/issues/7976
https://github.com/bscotch/ganary/actions/runs/11131505693 caught https://github.com/YoYoGames/GameMaker-Bugs/issues/7857

I am not discounting the challenges of maintaining CIs for a software as complex as GameMaker, and the fact that our CI is much smaller in scope compared to GM-TestFramework probably made it much easier to maintain. Still, I implore the maintainers of this repo to invest time into improving the stability of the CI, as it can be so helpful to catch issues early, give engine developers timely feedback on their code changes, and release more stable updates to the end users.

**Comment by YYDan** [comment]
Yeah, I agree with all of the above.

I did notice this one myself a while back, and so the problem was resolved (it was that the machine which hosts the GitHub runner was offline and so all CIs were timing-out), so I will close this one just now; however, this issue was also missed entirely until I just spotted it now. Apologies for that.

Thanks.
