### ISSUE TITLE
config.json is missing

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GM-TestFramework#28]
While `xUnit.yyp` mentions `config.json` among included files, it's missing, while it's crucial to run tests.

https://github.com/YoYoGames/GM-TestFramework/blob/b8305af069389d00b421df8f81d3681398e82ae4/projects/xUnit/xUnit.yyp#L52

I've tried to change `ConfigManager.loadFromFile` function so it logs warning instead of error and returns nothing if file not found, but in most places where `config_get("$$xxx$$")` is used, there's no handling of `undefined` value to give default one, so whole app still crashes.

**Comment by DiasFranciscoA** [comment]
The `config.json` file is automatically generated when running the framework from the command line. Due to the sensitive information it contains, we are unable to share the specific `config.json` file used. However, the framework has been updated to accommodate the changes required for running directly from the IDE without relying on the `config.json` file.
